apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 1 # Number of replicas/instances of your application
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp-container
        image: bhagyashreep/nodeapp_test:latest # Docker image name and tag
        ports:
        - containerPort: 4000 # Port on which your application listens
